apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    #assign external or client facing port to 9092
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: external
    #assign internal facing port to 29092
    - protocol: TCP
      port: 29092
      targetPort: 29092
      name: internal
---
# YOUR CODE HERE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.3
          imagePullPolicy: IfNotPresent
          ports:
            #assign two containerPort as one is 9092 which is external or client facing port
            - containerPort: 9092
            #other one is 29092 which is internal facing port
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-service:29092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          resources:
            #assign cpu 1 and memory 1gb
            limits:
              cpu: "1000m"
              memory: "1000Mi"
